# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Validate Schema and Docs
on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Test schemas
        run: uds run schema:test

      - name: Test docs
        run: uds run docs:test

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@42196a596353dc9f8acb21a6a86b5d4a4f7ee76f # v1.14.2
        with:
          suffix: validate-schema-and-docs
